# Generated by Django 3.1.3 on 2020-12-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtbooks',
            name='book_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
